added code for importing sequence reads
atlab/seq pull request #5
Opened 2017-04-12 22:21 UTC by dimitri-yatsenko

2017-04-13 07:51 UTC, cathryn1 commented on +seq/FlowCell.m
> +flow_cell                   : varchar(255)                  # flowcell used on this run
change to flowcell

2017-04-13 07:52 UTC, cathryn1 commented on +seq/Read.m
> +read_id                     : char(16)                      # machine-assigned id
did we decide to use the machine assigned id?  i think this is ok

2017-04-13 07:55 UTC, cathryn1 commented on +seq/SequencingPrimers.m
> +primers                     : varchar(30)                   # primers used for sequencing, e.g. Nextera s7+i5
change to seq_primers

2017-04-13 07:55 UTC, cathryn1 commented on pyseq/seq.py
> +    primers : varchar(30)  # primers used for sequencing, e.g. Nextera s7+i5
change to seq_primers

2017-04-13 07:56 UTC, cathryn1 commented on pyseq/seq.py
> +    size=null: tinyint unsigned # mean size of pooled cDNA sent for sequencing (in bp)
this needs to be smallint

2017-04-13 08:01 UTC, cathryn1 requested changes
Minor changes requested

2017-04-14 14:29 UTC, cathryn1 approved these changes

2017-04-14 14:32 UTC, cathryn1 requested changes
minor changes still need to be made

2017-04-14 14:36 UTC, dimitri-yatsenko commented on +seq/Read.m
> +read_id                     : char(16)                      # machine-assigned id
it will be more compact to use a number.  Is there any useful information in the machine-assigned id?

2017-04-14 14:50 UTC, dimitri-yatsenko commented on pyseq/seq.py
> +    size=null: tinyint unsigned # mean size of pooled cDNA sent for sequencing (in bp)
fixed

2017-04-14 14:50 UTC, dimitri-yatsenko commented on pyseq/seq.py
> +    primers : varchar(30)  # primers used for sequencing, e.g. Nextera s7+i5
fixed

2017-04-14 14:52 UTC, dimitri-yatsenko commented on +seq/SequencingPrimers.m
> +primers                     : varchar(30)                   # primers used for sequencing, e.g. Nextera s7+i5
fixed

2017-04-14 14:52 UTC, dimitri-yatsenko commented on +seq/FlowCell.m
> +flow_cell                   : varchar(255)                  # flowcell used on this run
fixed

2017-04-14 14:54 UTC, cathryn1 commented on +seq/Read.m
> +read_id                     : char(16)                      # machine-assigned id
i don't think there is useful information there and it should be ok to use a number

2017-04-14 14:55 UTC, cathryn1 approved these changes

2017-04-14 14:55 UTC, merged